language: cpp

os:
  - linux
  - osx
  - windows

compiler:
  - gcc
  - clang

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sdl2; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libegl1-mesa-dev libgles2-mesa-dev libsdl2-dev; fi
  - cmake .

script:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then devenv /build Release Inferno.sln; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" || "$TRAVIS_OS_NAME" == "linux" ]]; then make; fi