language: cpp

matrix:
  include:
    - os: osx
      compiler: clang

before_install:
    - eval "${MATRIX_EVAL}"

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install cmake; brew install sdl2; brew install devil; brew install boost; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libdevil-dev libegl1-mesa-dev libgles2-mesa-dev libsdl2-dev libboost-all-dev; fi
  - cmake .

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" || "$TRAVIS_OS_NAME" == "linux" ]]; then make; fi

