language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="brew install gcc && brew link gcc && CC=gcc-8 && CXX=g++-8"




before_install:
    - eval "${MATRIX_EVAL}"

before_script:
  - brew update; brew install libcxx; brew install cmake; brew install sdl2; brew install devil;
  - cmake .

script:
  - make;

